### ISSUE TITLE
How about CocoaHeads MN?

### ISSUE THREAD

**Issue by jonallured** [ohaimn/o.hai.mn#4]
Heyo! I found this project after your recent Tweet - how about adding CocoaHeads MN?

https://cocoaheadsmn.slack.com/

/cc @jonsteinmetz

**Comment by jimthedev** [comment]
Hi @jonallured,

That sounds cool. Do you have an invite site using something like [slackin](https://github.com/rauchg/slackin)? If not what is the best way for people to get invites?

Also let me know if there is some other info about CocoaHeads you'd like on there (meetup url / website).

Cheers,

Jim

**Comment by jonallured** [comment]
I'll defer to @jonsteinmetz since it's his group, but maybe something like this:

```
CocoaHeads Minnesota
Slack: https://cocoaheadsmn.slack.com/
Invites: Send an email to: cocoaheadsmn@pixelresearchlabs.com
```

**Comment by jonsteinmetz** [comment]
Thanks Jon, yes that information is correct. It would be great if you could add it to your site. Thanks.

**Comment by jimthedev** [comment]
Closed, you're listed at: https://o.hai.mn/#cocoaheadsmn
